# Generated by Django 3.2.6 on 2021-08-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineapp', '0002_auto_20210826_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
